#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          public
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for UrT Server
# Description:       Start/Stop/Restart the UrT service daemon
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

NAME=public
USER=chuck
GROUP=chuck
DIR=/home/chuck

su -c "cd $DIR && $DIR/start_public.sh $1" - $USER

