#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          Teamspeak
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for Teamspeak
# Description:       Start/Stop/Restart the Teamspeak service daemon
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

NAME=teamspeak
USER=chuck
DIR=/opt/teamspeak/
su -c "cd $DIR && $DIR/ts3server_startscript.sh $1" - $USER
